update curl and stuff

diff --git a/module/META-INF/zbin/setup b/module/META-INF/zbin/setup
--- a/module/META-INF/zbin/setup
+++ b/module/META-INF/zbin/setup
@@ -5,95 +5,68 @@
 true() { return 0; }
 false() { return 1; }
 echo2() { >&2 echo "$@"; }
-find_bin() { local IFS=":"; for path in $PATH; do [ -e "$path/$1" ] && echo "$path/$1" && break; done; }
-ui_print() { while [ "$1" ]; do (! $BOOTMODE && [ -e "$OUTFD" ]) && echo -e "ui_print $1\nui_print" >> $OUTFD || echo "$1"; shift; done; }
-defined() { while [ "$1" ]; do eval "[ -z \"\${${1}}\" ]" && return 1; shift; done; return 0; }
+ui_print() { for __ in "$@"; do [ "$BOOTMODE" == "false" -a -e "$OUTFD" ] && echo -e "ui_print $__\nui_print" >> $OUTFD || echo "$__"; done; }
 abort() { ui_print " " "$@" " "; exit 1; }
-import_info() { ( echo >> "$l/info.txt"; cat "$1" >> "$l/info.txt"; rm -f "$1" ) 2>/dev/null; }
-testrw() { local test return=0; for test; do if [ -d "$test" ]; then (rm -f "$test/.rw$$"; touch "$test/.rw$$" || echo > "$test/.rw$$") 2>/dev/null; if [ -f "$test/.rw$$" ]; then rm -f "$test/.rw$$"; else echo2 '!'"Read-Only: $test" && return=1; fi; else echo2 "Cant find: $test directory" && return=1; fi; done; return $return; }
-ensure_dir() { while [ "$1" ]; do ( rm -rf "$1" ) 2>/dev/null; mkdir -p "$1"; [ ! -d "$1" ] && abort "ERROR: Cant create folder $1"; shift; done; }
+import_info() { [ -f "$1" ] && { echo >> "$l/info.txt"; cat "$1" >> "$l/info.txt"; rm -f "$1" ; } ; }
+testrw() { for __ in "$@"; do { [ -d "$__" ] && { touch "$__/.rw$$" || echo > "$__/.rw$$" ; } 2>/dev/null && rm -f "$__/.rw$$"; } || { echo2 '!'"Read-Only: $__"; return 1; }; done; }
+ensure_dir() { for __ in "$@"; do rm -rf "$__" 2>/dev/null; mkdir -p "$__" || abort "ERROR: Cant create folder $__"; done; }
+is_substring() { case $2 in *"$1"*) return 0 ;; *) return 1 ;; esac; }
+is64bit() { __=$(od -An -t x1 -j 4 -N 1 "$1"); case $__ in *"02"*) return 0 ;; *"01"*) return 1 ;; *) echo2 "is64bit: Unknown $__: $1"; return 2 ;; esac; }
 
 #Advanced functions
-is_substring() {
-    case "$2" in
-        *"$1"*) return 0 ;;
-        *) return 1 ;;
-    esac
-}
 bbForArch() {
-   export ARCH
-   (rm -f $bb) 2>/dev/null;
    for ARCH in arch/*; do
-       if [ -d "$ARCH" ]; then
-          cp -f $ARCH/busybox $bb
-          chmod 755 $bb
-          if [ -x $bb ] && $bb >/dev/null 2>&1; then
-            ARCH=${ARCH##*/}
-            break
-          fi
-       fi
+      [ -d "$ARCH" ] || continue
+      cp -f $ARCH/busybox $bb; chmod 755 "$bb"
+      [ -x "$bb" ] && "$bb" >/dev/null 2>&1 && break
    done
-   [ ! -f "$bb" ] && abort "ERROR: Unsupported device architecture!"
+   [ -f "$bb" ] && ARCH=${ARCH##*/} || abort "ERROR: Unsupported device architecture!"
+}
+ensureArch() {
+  _f_=$(readlink -f /system/bin/sh 2>/dev/null || readlink /proc/$PPID/exe 2>/dev/null || readlink /proc/self/exe 2>/dev/null || ps | awk '/sh|busybox/{print $NF; exit}' 2>/dev/null)
+  [ -e "$_f_" ] && { is64bit "$_f_" || ARCH="armeabi-v7a" ; }
 }
 ensure_bin() {
-   local path bin result=1
-   [ -z "$bb" ] && bb=$(find_bin busybox)
-   while [ "$1" ]; do
-      if [ -z "$(command -v "$1")" ]; then
-         bin=$(find_bin $1); [ -n "$bin" ] && bin="\"$bin\""
-         if [ -z "$bin" -a -n "$bb" ] && "$bb" --list | "$bb" grep -Eq "^$1$"; then bin="\"$bb\" $1"; fi
-         if [ -n "$bin" ]; then eval "$1() { $bin \"\$@\"; }"; result=0
-         else $needed && abort "ERROR: Could not define \"$1\" binary" || return 1
-         fi
-      else
-         result=0
-      fi
-      shift;
-   done
-   return $result
+  _r_=0
+  for __ in "$@"; do
+    if ! command -v $__ >/dev/null; then
+      $bb_set || { bb_set=true; [ -n "$bb" ] && bb_list=" $(echo $("$bb" --list)) "; }
+      { [ -n "$bb" ] && is_substring " $__ " "$bb_list" ; } && eval "$__() { \"$bb\" $__ \"\$@\"; }" || { $needed && abort "ERROR: Could not define \"$__\" binary" || _r_=1; }
+    fi
+  done
+  return $_r_
 }
 setup_bb() {
-   #Try to ensure /system/bin/sh
-   needed=false; ensure_bin umount ln
-   if [ ! -f /system/bin/sh ]; then
-      umount -l /system 2>/dev/null
-      mkdir -p /system/bin
-      ln -sf "$(command -v sh)" /system/bin/sh
-   fi
-   if [ -e "$bb" ]; then
-     if ! echo "read me" | "$bb" grep -q "read me"; then
-        abort "ERROR:4: BusyBox cannot load on this device!"
-     elif ! "$bb" --install -s "$l"; then
-        for i in $("$bb" --list); do
-          if ! ln -sf "$bb" "$l/$i" && ! "$bb" ln -sf "$bb" "$l/$i" && ! "$bb" ln -f "$bb" "$l/$i"; then
-            # create script wrapper if symlinking and hardlinking failed because of restrictive selinux policy
-            if ! echo "#!$bb" > "$l/$i" || ! chmod 755 "$l/$i"; then
-              abort "ERROR:2: Failed to setup BusyBox"
-            fi
-          fi
-        done
-     fi
-   else
-      abort "ERROR:1: Cant find BusyBox"
-   fi
-   [ ! -f "$l/sh" ] && abort "ERROR:3: Failed to setup BusyBox"
+  needed=false; ensure_bin umount ln
+  [ ! -f /system/bin/sh ] && { umount -l /system 2>/dev/null; mkdir -p /system/bin; ln -sf "$(command -v sh)" /system/bin/sh; }
+  [ -e "$bb" ] || abort "ERROR:1: Cant find BusyBox"
+  if ! echo "read me" | "$bb" grep -q "read me"; then
+    abort "ERROR:4: BusyBox cannot load on this device!"
+  elif ! "$bb" --install -s "$l"; then
+    for i in $("$bb" --list); do
+      ln -sf "$bb" "$l/$i" || "$bb" ln -sf "$bb" "$l/$i" || "$bb" ln -f "$bb" "$l/$i" || {
+        echo "#!$bb" > "$l/$i" && chmod 755 "$l/$i" || abort "ERROR:2: Failed to setup BusyBox"
+      }
+    done
+  fi
+  [ -f "$l/sh" ] || abort "ERROR:3: Failed to setup BusyBox"
 }
 
-#Get BOOTMODE
-ps | grep zygote | grep -qv grep && export BOOTMODE=true || export BOOTMODE=false
-$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -qv grep && export BOOTMODE=true
+#BOOTMODE
+BOOTMODE=$( [ "$(getprop sys.boot_completed 2>/dev/null)" == 1 ] && echo true || { ps | grep -q "[z]ygote" || ps -A 2>/dev/null | grep -q "[z]ygote" && echo true || echo false ; } )
 
 #Start
 umask 022
 export PATH="/sbin:/system/bin:/sbin/su:/su/bin:/su/xbin:/system/xbin:/data/adb/magisk:/data/adb/ksu/bin:/data/adb/ap/bin:$PATH"
-needed=true; ensure_bin mkdir chmod cp
+bb_set=false; bb=$(command -v busybox)
+needed=true;  ensure_bin mkdir chmod cp
 needed=false; ensure_bin rm
 
 #Ensure Temp directory
 for TMP in /data/tmp /dev/tmp /cache/tmp /mnt/tmp /tmp; do
     mkdir -p $TMP 2>/dev/null; testrw $TMP && break || TMP=
 done
-[ -n "$TMP" ] && export TMP || abort "ERROR: Failed to create temporary directory"
+[ -n "$TMP" ] || abort "ERROR: Failed to create temporary directory"
 
 #ARGS
 while [ $# -gt 0 ]; do
@@ -127,13 +100,11 @@ while [ $# -gt 0 ]; do
 done
 
 #Global vars
-export MYPATH \
-TMPDIR="$TMP" \
+export TMPDIR="$TMP" \
 DNM="META-INF/com/google/android/magisk" \
-cert="META-INF/zbin/version.txt" \
 addons="$TMP/zbin/addons" \
 l="$TMP/zbin/ugu" \
-PERSISTDIR=/sbin/.magisk/mirror/persist
+TMP BOOTMODE OUTFD ZIPFILE PERSISTDIR CUSTOM_SETUP ARCH installzip
 
 #Extra
 rc="$TMP/0000001.tmp"
@@ -147,7 +118,7 @@ ensure_dir "$l" "$addons"
 #(Maintenance or just testing for Devs)
 if [ -f core -a -f static ]; then
    #Ensure BusyBox for ARCH
-   bb="$TMP/zbin/busybox"; bbForArch
+   bb_set=false; bb="$TMP/zbin/busybox"; bbForArch
    
    if ! $BOOTMODE; then
       export apex_mount=on
@@ -165,11 +136,14 @@ if [ -f core -a -f static ]; then
    #Ensure BusyBox Environment
    setup_bb; export PATH="$l:$PATH"
    
+   #Rectify ARCH for 32bit devices
+   ensureArch
+   
    #Loading bin & static
    for bin in "arch/$ARCH/bin" static; do
       if [ -f "$bin" ]; then
-         unzip -qo "$bin" -d "$TMP/zbin"
-         import_info "$TMP/zbin/info.txt"
+         unzip -qo "$bin" -d "$addons"
+         import_info "$addons/info.txt"
       else
          abort "ERROR: Cant get $bin"
       fi
@@ -178,19 +152,23 @@ if [ -f core -a -f static ]; then
    #Loading extra.zip (Optional)
    if [ -f "extra.zip" ]; then
       if is_substring $ARCH "$(unzip -l "extra.zip" "$ARCH/")"; then
-         unzip -qoj extra.zip "$ARCH/*" -d "$TMP/zbin"
-         import_info "$TMP/zbin/info.txt"
+         unzip -qoj extra.zip "$ARCH/*" -d "$addons"
+         import_info "$addons/info.txt"
       else
          echo2 "setup: extra.zip does not include additions to your architecture"
       fi
    fi
    
+   #Getting version
+   export di_version=$(grep -Eo "[0-9]+\.[0-9]+[-[:alnum:]]*" version.txt 2>/dev/null)
+   
    #Getting configs
    cp -f configs/* -t "$l"
   
    #Finish
-   find "$TMP/zbin" -type f ! -name "busybox" -exec mv -f {} "$l" \;
-   find "$l" -type f -exec chmod 755 {} +;
+   chmod -R 755 "$addons"
+   mv -f "$addons"/* -t "$l"
+   
    echo '
    shopt -s checkwinsize
    export HISTFILE="'$TMP'/zbin/bash_history"
